### ISSUE TITLE
Chart Data

### ISSUE THREAD

**Issue by GBratsos** [enamelizer/DR2Rallymaster#2]
Hello,

I just wanted to ask what is Chart Data and Negated Chart Data. What do their values mean.

**Comment by enamelizer** [comment]
Hi @GBratsos sorry for the delay, I missed this. The chart data allows you to create position charts of driver position changes over the rally like the attached image. The "negated" version is for use in Google Sheets as it does not allow you to reverse the order (so first place is on top, etc).

See the attached image for an example of how to use it.
![image](https://user-images.githubusercontent.com/5801754/80425521-a43ba400-8898-11ea-8a52-abe24a05e8df.png)

**Comment by GBratsos** [comment]
Hello @enamelizer and thank you for the answer.

Do you know how can i create a chart like the one you posted in Google Sheets with the negated data?

**Comment by enamelizer** [comment]
@GBratsos 
1. Highlight the data that will go into the chart, including the names
2. Select Insert -> Chart from the top menu in Sheets
3. In the "Chart Editor" menu, Chart Type = Line, at the bottom select "Switch rows / columns"
4. (Optional) In "Chart Editor" -> Customize -> Major gridline count -> None
5. (Optional) Resize chart and legend font to line up the lines with the driver names

**Comment by GBratsos** [comment]
Awesome, thanks for helping me. I will try this :)
