### ISSUE TITLE
Issue logging in.

### ISSUE THREAD

**Issue by zisekoz** [enamelizer/DR2Rallymaster#3]
Codemasters have changed the URL to Dirtrally2.com. So unable to login now.

**Comment by enamelizer** [comment]
Thanks for the heads up, I will try to address this today by making the login URL a setting instead of hard coded in the application.

**Comment by zisekoz** [comment]
Awesome man! :)

**Comment by enamelizer** [comment]
Updated the tool to allow the URL to be settable, with the new URL as the default.

You can get the fixed version here: https://github.com/enamelizer/DR2Rallymaster/releases/tag/v1.3

**Comment by zisekoz** [comment]
Awesome! it's such a good tool. thank you :)

**Comment by enamelizer** [comment]
Whoops forgot to update this sorry! If you didn't already see it I fixed this in a342f652ac41d06c61dc96656a821f23ff646802 and made release v1.3 to address this. Glad you find it useful
