### ISSUE TITLE
login with steam not working

### ISSUE THREAD

**Issue by ilcavero** [enamelizer/DR2Rallymaster#5]
Hi, I wanted to check out your project but I need to login to racenet with steam and after I put my username and password it should show a modal screen for the 2FA code but it seems that something in the embedded browser blocks the modal so it just blinks and doesn't appear. Is there a way to overcome this?

Not knowing your project existed I wrote https://github.com/ilcavero/dirtscrapper which leaves it to the user to manually copy the request headers from the browser network debug tab into a file. I was interested to see what other things were different in yours.

**Comment by enamelizer** [comment]
Unfortunately there is no way to login with steam without modifying it to take the authentication cookies from another source. It is using the WinForms WebBrowser control which is pretty broken and based on old IE, but I didn't want to embed a 3rd party browser like chromium into it.
