### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by cargorallyeteam** [enamelizer/DR2Rallymaster#7]
Hello!

I want to ask for help on how to make the program work? Unfortunately I didn't really get it so I want to ask for help. Step by step. Thanks!

**Comment by enamelizer** [comment]
I made a video recently on my process for results scoring. The tool is just one part of how I score a championship so the video is kind of long, but you can see a how-to on using the tool at around 11:16 on this video [https://youtu.be/bCO1fOBigjM?t=676](url)

The club ID in that video comes from the URL of the club on the dirtgame.com for example if you go to a club page https://dirtrally2.dirtgame.com/clubs/club/239655 - the number at the end of that URL is your club id (239655).
